### ISSUE TITLE
add km tag for mindistance and maxdistance variables

### ISSUE THREAD

**Issue by carltape** [adjtomo/pysep#104] opened 2023-03-09 21:23 UTC
mindistance and maxdistance require km, so it'd be safer to have this tag in the variable name, since otherwise people might try distance in degrees (like 0 to 180).

**Comment by aakash10gupta** [comment] 2023-03-11 02:24
I tested the update and the new argument names are working fine while the old ones no longer work. If that was the intended behavior after the update, then we can close this issue.

**Comment by carltape** [comment] 2023-03-11 05:38
Yep, that's intended. Let's leave the issue open until we update all the variable names in the 626 folders.

**Comment by aakash10gupta** [comment] 2023-06-03 02:01
The variable names have been updated. This issue can be closed.

**Closed** 2023-06-05 04:35 UTC
Labels: enhancement
